export const AUTH_ACTION_TYPES = {
    LOGIN: 'LOGIN',
    // REGISTER: 'REGISTER',
    UPDATE: 'USER_UPDATE',
    AUTH_FAILED: 'AUTH_FAILED',
    RESET_AUTH_STATE: 'RESET_AUTH_STATE',
    LOGOUT: 'LOGOUT',
}
export const CATEGORIES_ACTION_TYPES = {
    GET: 'GET',
    UPDATE: 'CATEGORY_UPDATE',
    DELETE: 'CATEGORY_DELETE',
    ADD: 'CATEGORY_ADD',
}
export const ALLERGIES_ACTION_TYPES = {
    GET: 'GET_ALLERGIES',
    UPDATE: 'ALLERGY_UPDATE',
    DELETE: 'ALLERGY_DELETE',
    ADD: 'ALLERGY_ADD',
}
export const ARTICLES_ACTION_TYPES = {
    GET: 'GET_ARTICLES',
    UPDATE: 'ARTICLES_UPDATE',
    DELETE: 'ARTICLES_DELETE',
    ADD: 'ARTICLES_ADD',
}
export const CUSTOMERS_ACTION_TYPES = {
    GET: 'GET_CUSTOMERS',
    UPDATE: 'CUSTOMERS_UPDATE',
    DELETE: 'CUSTOMER_DELETE',
    ADD: 'CUSTOMER_ADD',
}
export const COUPONS_ACTION_TYPES = {
    GET: 'GET_COUPONS',
    UPDATE: 'COUPONS_UPDATE',
    DELETE: 'COUPON_DELETE',
    ADD: 'COUPON_ADD',
}
export const RECIPE_BOOK_ACTION_TYPES = {
    GET: 'GET_RECIPEOOKS',
    UPDATE: 'RECIPEOOKS_UPDATE',
    DELETE: 'RECIPEOOK_DELETE',
    ADD: 'RECIPEOOK_ADD',
}
export const PROFILES_ACTION_TYPES = {
    GET: 'GET_PROFILES',
    UPDATE: 'PROFILES_UPDATE',
    DELETE: 'PROFILE_DELETE',
    ADD: 'PROFILE_ADD',
}
export const AVATAR_ACTION_TYPES = {
    GET: 'GET_AVATARS',
    UPDATE: 'AVATARS_UPDATE',
    DELETE: 'AVATAR_DELETE',
    ADD: 'AVATAR_ADD',
}
export const DEFAULT_FOOD_ACTION_TYPES = {
    GET: 'GET_DEFAULT_FOODS',
    UPDATE: 'DEFAULT_FOODS_UPDATE',
    DELETE: 'DEFAULT_FOOD_DELETE',
    ADD: 'DEFAULT_FOOD_ADD',
    CATEGORY_SELECTED: 'SELECTED_CATEGORY_FOR_FOOD',
}
export const NOTIFICATION_ACTION_TYPES = {
    GET: 'GET_NOTIFICATIONS',
    UPDATE: 'NOTIFICATIONS_UPDATE',
    DELETE: 'NOTIFICATION_DELETE',
    ADD: 'NOTIFICATION_ADD',
    CLEAR: 'CLEAR_NOTIFICATION',
}
